/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package communication;

import java.io.Serializable;

/**
 *
 * @author User
 */
public enum Operation implements Serializable {
    LOGIN, ADMIN_LOGIN,ADD_USER, NOTIFY, EXIT,CLOSE,
    ADD_LOVACKO_DRUSTVO, DELETE_LOVACKO_DRUSTVO, SEARCH_LOVACKO_DRUSTVO, GET_ALL_LOVACKO_DRUSTVO, UPDATE_LOVACKO_DRUSTVO, GET_ALL_DRUSTVO_NOPRICES,
    ADD_ANIMAL, DELETE_ANIMAL, UPDATE_ANIMAL, GET_ALL_ANIMALS, SEARCH_ANIMAL,GET_ALL_ANIMALS_BY_ALLOWED_BY_DRUSTVO_BY_SEASON,
    GET_ALL_PRICES, GET_ALL_PRICES_BY_SEASON, ADD_ALL_PRICES, UPDATE_PRICES, DELETE_PRICES, SEARCH_PRICES,
    UPDATE_HUNTER, SEARCH_HUNTER, DELETE_HUNTER, GET_ALL_HUNTER,
    RESERVATE, GET_ALL_RESERVATION, GET_ALL_RESERVATION_BY_SEASON, DELETE_RESERVATION,GET_ALL_RESERVATION_BY_SEASON_BY_DRUSTVO_NO_INVOICE,
    GET_ALL_SEASON, ADD_POREZ, UPDATE_POREZ, SEARCH_POREZ, DELETE_POREZ,
    GET_ALL_PROFITS_PER_SEASON, GET_HUNTED_ANIMALS_NUM,
    GET_INVOICE_ITEMS_BY_RESERVATION,
    GET_ALL_INVOICE_BY_DRUSTVO,ADD_INVOICE,UPDATE_INVOICE
    

}
