/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.form.design;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        try {
        
            initComponents();
            prepareView();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void prepareView() throws IOException {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Image slika=ImageIO.read(ClassLoader.getSystemResource("Icons/125-godina.jpg")).getScaledInstance(MainForm.this.getWidth(), MainForm.this.getHeight(), WIDTH);
        lblSlika.setIcon(new ImageIcon(slika));
        pnlOverlay.setMinimumSize(new Dimension(MainForm.this.getWidth(), MainForm.this.getHeight()));
        lblSlika.setMinimumSize(new Dimension(MainForm.this.getWidth(), MainForm.this.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOverlay = new javax.swing.JPanel();
        lblSlika = new javax.swing.JLabel();
        pnlServer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuItemServer = new javax.swing.JMenuItem();
        menuItemDatabase = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavni Meni");
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlOverlay.setMaximumSize(new java.awt.Dimension(2000, 2000));
        pnlOverlay.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlOverlay.setOpaque(false);

        lblSlika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/125-godina.jpg"))); // NOI18N
        lblSlika.setMaximumSize(new java.awt.Dimension(2000, 2000));

        pnlServer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        javax.swing.GroupLayout pnlOverlayLayout = new javax.swing.GroupLayout(pnlOverlay);
        pnlOverlay.setLayout(pnlOverlayLayout);
        pnlOverlayLayout.setHorizontalGroup(
            pnlOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServer, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 1550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlOverlayLayout.setVerticalGroup(
            pnlOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(pnlOverlay, "card2");

        jMenu3.setText(" Konfiguracija");

        menuItemServer.setText(" Server");
        jMenu3.add(menuItemServer);

        menuItemDatabase.setText("Baza Podataka");
        jMenu3.add(menuItemDatabase);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getMenuItemDatabase() {
        return menuItemDatabase;
    }

    public JMenuItem getMenuItemServer() {
        return menuItemServer;
    }




    public JPanel getPnlOverlay() {
        return pnlOverlay;
    }

    public JPanel getPnlServer() {
        return pnlServer;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JMenuItem menuItemDatabase;
    private javax.swing.JMenuItem menuItemServer;
    private javax.swing.JPanel pnlOverlay;
    private javax.swing.JPanel pnlServer;
    // End of variables declaration//GEN-END:variables
}
