/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.form.components;

import communication.Response;
import communication.ResponseType;
import domain.Animal;
import domain.LovackoDrustvo;
import domain.Reservation;
import static java.awt.image.ImageObserver.WIDTH;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import project.form.conroller.cordinator.MainControllerCordinator;

/**
 *
 * @author User
 */
public class NotificationComponent extends javax.swing.JPanel {

    /**
     * Creates new form NotificationComponent
     */
    public NotificationComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        lblMessage.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMessageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessageMouseClicked
        MainControllerCordinator.getInstance().getFrmMain().getPnlMessages().remove(this);
        MainControllerCordinator.getInstance().getFrmMain().getPnlMessages().revalidate();
        MainControllerCordinator.getInstance().getFrmMain().getPnlMessages().repaint();

    }//GEN-LAST:event_lblMessageMouseClicked

    public JLabel getLblIcon() {
        return lblIcon;
    }

    public JLabel getLblMessage() {
        return lblMessage;
    }

    public void prepareComponent(Response response) {
        try {
            if (response.getArgument() instanceof Reservation) {

                if (response.getResponseType().equals(ResponseType.ERROR)) {

                    lblIcon.setIcon(new ImageIcon(ImageIO.read(ClassLoader.getSystemResource("icon/cancelled.png")).getScaledInstance(30, 30, WIDTH)));
                    lblMessage.setText(((Reservation) response.getArgument()).getHunter().getpassportNo() + " je otkazao rezervaciju za sezonu " + ((Reservation) response.getArgument()).getSeason());

                } else {
                    lblIcon.setIcon(new ImageIcon(ImageIO.read(ClassLoader.getSystemResource("icon/reservation.png")).getScaledInstance(30, 30, WIDTH)));
                    lblMessage.setText(((Reservation) response.getArgument()).getHunter().getpassportNo() + " je rezervisao za sezonu " + ((Reservation) response.getArgument()).getSeason());
                }

            } else if (response.getArgument() instanceof Animal) {
                lblIcon.setIcon(new ImageIcon(ImageIO.read(ClassLoader.getSystemResource("icon/forbidden.png")).getScaledInstance(30, 30, WIDTH)));
                lblMessage.setText("Za zivotinju " + ((Animal) response.getArgument()).getShortName() + " je lov zabranjen");

            } else if (response.getArgument() instanceof LovackoDrustvo) {
                lblIcon.setIcon(new ImageIcon(ImageIO.read(ClassLoader.getSystemResource("icon/warning.png")).getScaledInstance(30, 30, WIDTH)));
                lblMessage.setText(response.getPoruka());

            } else {
                System.out.println("Greska");
            }
            MainControllerCordinator.getInstance().getFrmMain().getPnlMessages().add(this);
            MainControllerCordinator.getInstance().getFrmMain().getPnlMessages().revalidate();
            MainControllerCordinator.getInstance().getFrmMain().getPnlMessages().repaint();
        } catch (Exception e) 
        
        {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
