/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.form.design;


import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import project.form.controller.cordinator.MainFormControllerCordinator;


/**
 *
 * @author User
 */
public class LovackoDrustvoReservationForm extends JFrame {

   
  
    /**
     * Creates new form TestAnimalPanel
     */
    public LovackoDrustvoReservationForm() {
        
     initComponents();
     
        setMinimumSize(new Dimension(MainFormControllerCordinator.getInstance().getFrmMain().getWidth()-50, MainFormControllerCordinator.getInstance().getFrmMain().getHeight()-50));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlAnimal = new javax.swing.JPanel();
        pnlPrices = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPrices = new javax.swing.JTable();
        btnEnterHunter = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pnlLovackoDrustvo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSeason = new javax.swing.JLabel();
        btnSeason = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rezervacija");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnlAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAnimalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAnimalMouseEntered(evt);
            }
        });
        pnlAnimal.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(pnlAnimal);

        pnlPrices.setBorder(javax.swing.BorderFactory.createTitledBorder("Cenovnik"));
        pnlPrices.setLayout(new java.awt.BorderLayout());

        tblPrices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPrices);

        pnlPrices.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnEnterHunter.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnEnterHunter.setText("Unesi Podatke Lovca");
        btnEnterHunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterHunterActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnBack.setText("Nazad do glavne forme");

        pnlLovackoDrustvo.setLayout(new java.awt.BorderLayout());
        jScrollPane3.setViewportView(pnlLovackoDrustvo);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sezona"));

        lblSeason.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        lblSeason.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(lblSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSeason.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        btnSeason.setText("Izaberi drugu sezonu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlPrices, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEnterHunter, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                    .addComponent(btnSeason, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlPrices, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnEnterHunter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSeason, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    
    }//GEN-LAST:event_formMouseClicked

    private void btnEnterHunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterHunterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterHunterActionPerformed

    private void pnlAnimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnimalMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlAnimalMouseEntered

    private void pnlAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnimalMouseClicked
        // TODO add your handling code here:

        // listLovackoDrustvo.clearSelection();
    }//GEN-LAST:event_pnlAnimalMouseClicked

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnterHunter;
    private javax.swing.JButton btnSeason;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSeason;
    private javax.swing.JPanel pnlAnimal;
    private javax.swing.JPanel pnlLovackoDrustvo;
    private javax.swing.JPanel pnlPrices;
    private javax.swing.JTable tblPrices;
    // End of variables declaration//GEN-END:variables



    public JPanel getPnlLovackoDrustvo() {
        return pnlLovackoDrustvo;
    }
      public JPanel getPnlAnimal() {
        return pnlAnimal;
    }

    public JPanel getPnlPrices() {
        return pnlPrices;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnSeason() {
        return btnSeason;
    }
    
    

    public JButton getBtnEnterHunter() {
        return btnEnterHunter;
    }

    public JTable getTblPrices() {
        return tblPrices;
    }

    public JLabel getLblSeason() {
        return lblSeason;
    }

  

    
      
}
