/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.form.design;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        try {
        
            initComponents();
            prepareView();
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void prepareView() throws IOException {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Image slika=ImageIO.read(ClassLoader.getSystemResource("Icons/125-godina.jpg")).getScaledInstance(MainForm.this.getWidth(), MainForm.this.getHeight(), WIDTH);
        lblSlika.setIcon(new ImageIcon(slika));
        pnlOverlay.setMinimumSize(new Dimension(MainForm.this.getWidth(), MainForm.this.getHeight()));
        lblSlika.setMinimumSize(new Dimension(MainForm.this.getWidth(), MainForm.this.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOverlay = new javax.swing.JPanel();
        lblSlika = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLovackoDrustvo = new javax.swing.JMenu();
        menuItemAddDrustvo = new javax.swing.JMenuItem();
        menuItemUpdateDrustvo = new javax.swing.JMenuItem();
        menuItemAddUser = new javax.swing.JMenuItem();
        menuDivljac = new javax.swing.JMenu();
        mnItmAddAnimal = new javax.swing.JMenuItem();
        mnItmChangeAnimal = new javax.swing.JMenuItem();
        menuItemHunter = new javax.swing.JMenu();
        menuItemDeleteHunter = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemReservate = new javax.swing.JMenuItem();
        menuItemViewReservation = new javax.swing.JMenuItem();
        menuItemUpdateReservation = new javax.swing.JMenuItem();
        menuItemRequestPrices = new javax.swing.JMenu();
        menuItemAddSeason = new javax.swing.JMenuItem();
        menuItemUpdateSeason = new javax.swing.JMenuItem();
        menuItemNotifyDrustvoPrices = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemFinance = new javax.swing.JMenuItem();
        menuItemHuntedAnimalPerSeason = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavni Meni");
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlOverlay.setMaximumSize(new java.awt.Dimension(2000, 2000));
        pnlOverlay.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlOverlay.setOpaque(false);

        lblSlika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/125-godina.jpg"))); // NOI18N
        lblSlika.setMaximumSize(new java.awt.Dimension(2000, 2000));

        javax.swing.GroupLayout pnlOverlayLayout = new javax.swing.GroupLayout(pnlOverlay);
        pnlOverlay.setLayout(pnlOverlayLayout);
        pnlOverlayLayout.setHorizontalGroup(
            pnlOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 1626, Short.MAX_VALUE)
        );
        pnlOverlayLayout.setVerticalGroup(
            pnlOverlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        getContentPane().add(pnlOverlay, "card2");

        menuLovackoDrustvo.setText("Lovacko Drustvo");

        menuItemAddDrustvo.setText(" Dodaj Lovacko Drustvo");
        menuItemAddDrustvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddDrustvoActionPerformed(evt);
            }
        });
        menuLovackoDrustvo.add(menuItemAddDrustvo);

        menuItemUpdateDrustvo.setText(" Izmeni Lovacko Drustvo");
        menuLovackoDrustvo.add(menuItemUpdateDrustvo);

        menuItemAddUser.setText("Dodaj korisnika");
        menuLovackoDrustvo.add(menuItemAddUser);

        jMenuBar1.add(menuLovackoDrustvo);

        menuDivljac.setText(" Divljac");

        mnItmAddAnimal.setText(" Dodaj");
        mnItmAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItmAddAnimalActionPerformed(evt);
            }
        });
        menuDivljac.add(mnItmAddAnimal);

        mnItmChangeAnimal.setText(" Izmeni");
        mnItmChangeAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItmChangeAnimalActionPerformed(evt);
            }
        });
        menuDivljac.add(mnItmChangeAnimal);

        jMenuBar1.add(menuDivljac);

        menuItemHunter.setText("Lovac");

        menuItemDeleteHunter.setText(" Obrisi");
        menuItemHunter.add(menuItemDeleteHunter);

        jMenuBar1.add(menuItemHunter);

        jMenu1.setText(" Rezervacija");

        menuItemReservate.setText(" Rezervisi");
        jMenu1.add(menuItemReservate);

        menuItemViewReservation.setText("Pogledaj");
        jMenu1.add(menuItemViewReservation);

        menuItemUpdateReservation.setText("Ponisti");
        menuItemUpdateReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateReservationActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemUpdateReservation);

        jMenuBar1.add(jMenu1);

        menuItemRequestPrices.setText(" Sezona");

        menuItemAddSeason.setText(" Dodaj");
        menuItemRequestPrices.add(menuItemAddSeason);

        menuItemUpdateSeason.setText("Izmeni");
        menuItemRequestPrices.add(menuItemUpdateSeason);

        menuItemNotifyDrustvoPrices.setText(" Zahtev za cenovnik");
        menuItemNotifyDrustvoPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNotifyDrustvoPricesActionPerformed(evt);
            }
        });
        menuItemRequestPrices.add(menuItemNotifyDrustvoPrices);

        jMenuBar1.add(menuItemRequestPrices);

        jMenu2.setText(" Izvestaj");

        menuItemFinance.setText(" Finansije");
        jMenu2.add(menuItemFinance);

        menuItemHuntedAnimalPerSeason.setText("Ulov po sezoni");
        jMenu2.add(menuItemHuntedAnimalPerSeason);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddDrustvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddDrustvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAddDrustvoActionPerformed

    private void mnItmChangeAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItmChangeAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnItmChangeAnimalActionPerformed

    private void mnItmAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItmAddAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnItmAddAnimalActionPerformed

    private void menuItemUpdateReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUpdateReservationActionPerformed

    private void menuItemNotifyDrustvoPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNotifyDrustvoPricesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemNotifyDrustvoPricesActionPerformed

 
    public JMenuItem getMenuItemAddDrustvo() {
        return menuItemAddDrustvo;
    }

    public JPanel getPnlOverlay() {
        return pnlOverlay;
    }


    public JMenuItem getMenuItemNotifyDrustvoPrices() {
        return menuItemNotifyDrustvoPrices;
    }

    public JMenuItem getMenuItemAddUser() {
        return menuItemAddUser;
    }

   

  


    public JMenuItem getMenuItemDeleteHunter() {
        return menuItemDeleteHunter;
    }

    public JMenu getMenuItemHunter() {
        return menuItemHunter;
    }

    public JMenuItem getMnItemChangeDrustvo() {
        return menuItemUpdateDrustvo;
    }

    public JMenuItem getMnItmAddAnimal() {
        return mnItmAddAnimal;
    }

    public JMenuItem getMenuItemUpdateDrustvo() {
        return menuItemUpdateDrustvo;
    }

    public JMenuItem getMenuItemAddSeason() {
        return menuItemAddSeason;
    }

    public JMenuItem getMenuItemFinance() {
        return menuItemFinance;
    }

    public JMenuItem getMenuItemHuntedAnimalPerSeason() {
        return menuItemHuntedAnimalPerSeason;
    }

    public JMenu getMenuItemRequestPrices() {
        return menuItemRequestPrices;
    }

    public JMenuItem getMenuItemUpdateReservation() {
        return menuItemUpdateReservation;
    }

    public JMenuItem getMenuItemUpdateSeason() {
        return menuItemUpdateSeason;
    }

    public JMenuItem getMenuItemViewReservation() {
        return menuItemViewReservation;
    }

  

   

    public JMenuItem getMenuItemReservate() {
        return menuItemReservate;
    }

    public JMenuItem getMnItmChangeAnimal() {
        return mnItmChangeAnimal;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JMenu menuDivljac;
    private javax.swing.JMenuItem menuItemAddDrustvo;
    private javax.swing.JMenuItem menuItemAddSeason;
    private javax.swing.JMenuItem menuItemAddUser;
    private javax.swing.JMenuItem menuItemDeleteHunter;
    private javax.swing.JMenuItem menuItemFinance;
    private javax.swing.JMenuItem menuItemHuntedAnimalPerSeason;
    private javax.swing.JMenu menuItemHunter;
    private javax.swing.JMenuItem menuItemNotifyDrustvoPrices;
    private javax.swing.JMenu menuItemRequestPrices;
    private javax.swing.JMenuItem menuItemReservate;
    private javax.swing.JMenuItem menuItemUpdateDrustvo;
    private javax.swing.JMenuItem menuItemUpdateReservation;
    private javax.swing.JMenuItem menuItemUpdateSeason;
    private javax.swing.JMenuItem menuItemViewReservation;
    private javax.swing.JMenu menuLovackoDrustvo;
    private javax.swing.JMenuItem mnItmAddAnimal;
    private javax.swing.JMenuItem mnItmChangeAnimal;
    private javax.swing.JPanel pnlOverlay;
    // End of variables declaration//GEN-END:variables
}
