/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.form.components;


import domain.Animal;
import project.form.controller.LovackoDrustvoReservationFormController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

import project.form.components.decorator.IComponentFilter;


/**
 *
 * @author User
 */
public class AnimalPanelComponent extends JPanel implements IComponentFilter<AnimalToggleComponent> {

    /**
     * Creates new form PanelAnimals
     */
   
    LovackoDrustvoReservationFormController resFrmController;
    
    
    public AnimalPanelComponent(LovackoDrustvoReservationFormController resFrmController) {
        initComponents();
        this.resFrmController= resFrmController;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAnimlas = new javax.swing.JPanel();

        pnlAnimlas.setLayout(new java.awt.GridLayout(0, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAnimlas, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAnimlas, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlAnimlas;
    // End of variables declaration//GEN-END:variables

    @Override // vracaju se sve animal componente po sezoni
    public List<AnimalToggleComponent> getItems() {
        List<AnimalToggleComponent> animalComponents = new ArrayList<>();
        List<Animal> animals = resFrmController.getAnimalsBySeason();
        for (Animal animal : animals) {
            AnimalToggleComponent animalComponent= new AnimalToggleComponent(animal);
            resFrmController.setPnlAnimalsListeners(animalComponent);
            animalComponents.add(animalComponent);
            
        }
        return animalComponents;
    }

    @Override
    public String getDomainName() {
        return "Divljac";
    }

    @Override
    public void clear() {
        pnlAnimlas.removeAll();
        pnlAnimlas.revalidate();
        pnlAnimlas.repaint();
    }

    @Override
    public void addItem(AnimalToggleComponent item) {
        resFrmController.setPnlAnimalsListeners(item);
        pnlAnimlas.add(item);
        pnlAnimlas.revalidate();
        pnlAnimlas.repaint();
        
    }

  

    public static boolean Filter(AnimalToggleComponent item, String str) {
        return item.getAnimal().getName().toLowerCase().contains(str.toLowerCase());
    }

    public JPanel getPnlAnimlas() {
        return pnlAnimlas;
    }

   
    
}
