/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.form.components;



import domain.LovackoDrustvo;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;




import project.form.components.decorator.IComponentFilter;

/**
 *
 * @author User
 */
public class LovackoDrustvoListComponent extends javax.swing.JPanel implements IComponentFilter<LovackoDrustvo>{

    /**
     * Creates new form LovackoDrustvoListComponent
     */
    
    private JList<LovackoDrustvo> jList;  // instanca Jliste
    private List<LovackoDrustvo> drustva;

   
    
   

    public LovackoDrustvoListComponent() {
        initComponents();
       
        

        prepareComponents();
        
        pnlList.add(jList);

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlList = new javax.swing.JPanel();

        pnlList.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  
    public static boolean Filter(LovackoDrustvo drustvo, String str) {
        return drustvo.getName().toLowerCase().contains(str.toLowerCase());
    }

    private void prepareComponents() {
        
        jList = new JList<>();

    }

    

    public JList<LovackoDrustvo> getjList() {
        return jList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlList;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<LovackoDrustvo> getItems() {
        
        return drustva;
    }

    @Override
    public String getDomainName() {
        return "Lovacko Drustvo";
    }

   

    @Override
    public void clear() {
        ((DefaultListModel)jList.getModel()).clear();
    }

   

    @Override
    public void addItem(LovackoDrustvo item) {
        ((DefaultListModel)jList.getModel()).addElement(item);
    }
    
     public void setDrustva(List<LovackoDrustvo> drustva) {
        this.drustva = drustva;
    }
}
